-- CreateTable
CREATE TABLE "listening_days" (
    "user_id" UUID NOT NULL,
    "book_id" UUID NOT NULL,
    "day" TEXT NOT NULL,
    "seconds_listened" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "listening_days_pkey" PRIMARY KEY ("user_id","book_id","day")
);

-- CreateIndex
CREATE INDEX "listening_days_user_id_day_idx" ON "listening_days"("user_id", "day");

-- AddForeignKey
ALTER TABLE "listening_days" ADD CONSTRAINT "listening_days_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- =============================================================================
-- Not generated by Prisma.
-- =============================================================================
ALTER TABLE "listening_days" ADD CONSTRAINT "listening_days_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users ("id") ON DELETE CASCADE;

ALTER TABLE "listening_days" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS listening_days_owner_all ON public.listening_days;
CREATE POLICY listening_days_owner_all ON public.listening_days
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Accumulate rather than overwrite: the player flushes deltas, and two devices
-- listening on the same day must add up instead of clobbering one another.
CREATE OR REPLACE FUNCTION public.add_listening(
  p_book_id uuid, p_day text, p_seconds integer
) RETURNS void
LANGUAGE sql SECURITY INVOKER
AS $$
  INSERT INTO public.listening_days (user_id, book_id, day, seconds_listened, updated_at)
  VALUES (auth.uid(), p_book_id, p_day, GREATEST(p_seconds, 0), now())
  ON CONFLICT (user_id, book_id, day) DO UPDATE
    SET seconds_listened = public.listening_days.seconds_listened + GREATEST(p_seconds, 0),
        updated_at = now();
$$;
