-- =============================================================================
-- Lock down Prisma's own bookkeeping table.
--
-- Prisma creates public._prisma_migrations, and Supabase exposes the whole
-- public schema through PostgREST. Left as-is it has no row-level security, so
-- anyone holding the (publishable) anon key could read the migration history.
--
-- Prisma connects as the table's owner, and owners bypass RLS unless FORCE ROW
-- LEVEL SECURITY is set, so this does not affect migrations.
--
-- Not generated by Prisma — hand-written.
-- =============================================================================
ALTER TABLE public._prisma_migrations ENABLE ROW LEVEL SECURITY;

-- No policies are created, so PostgREST's roles get nothing. The REVOKE is
-- belt-and-braces, guarded because these roles are Supabase-specific.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON public._prisma_migrations FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON public._prisma_migrations FROM authenticated;
  END IF;
END;
$$;
