-- =============================================================================
-- Audiobook Viewer — initial migration
--
-- The first half is generated from prisma/schema.prisma via:
--   npm run db:diff
--
-- The second half is hand-maintained SQL for things Prisma cannot express:
-- foreign keys into Supabase's auth schema, row-level security, the updated_at
-- trigger, and the cover-art storage bucket. Keep both halves in this file.
-- =============================================================================

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "source_kind" AS ENUM ('multi_file', 'single_file_chapters', 'single_file');

-- CreateTable
CREATE TABLE "books" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "author" TEXT,
    "cover_url" TEXT,
    "source_kind" "source_kind" NOT NULL,
    "folder_label" TEXT NOT NULL,
    "total_duration_sec" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "books_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chapters" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "book_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "idx" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "start_sec" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "end_sec" DOUBLE PRECISION,
    "duration_sec" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "book_offset_sec" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "chapters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "progress" (
    "book_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "chapter_idx" INTEGER NOT NULL DEFAULT 0,
    "position_sec" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "book_position_sec" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "progress_pkey" PRIMARY KEY ("book_id")
);

-- CreateTable
CREATE TABLE "bookmarks" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "book_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "chapter_idx" INTEGER NOT NULL,
    "position_sec" DOUBLE PRECISION NOT NULL,
    "label" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "bookmarks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "device_sources" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "device_id" TEXT NOT NULL,
    "device_label" TEXT NOT NULL,
    "book_id" UUID NOT NULL,
    "folder_label" TEXT NOT NULL,
    "last_verified_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "device_sources_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "books_user_id_idx" ON "books"("user_id");

-- CreateIndex
CREATE INDEX "chapters_book_id_idx_idx" ON "chapters"("book_id", "idx");

-- CreateIndex
CREATE UNIQUE INDEX "chapters_book_id_idx_key" ON "chapters"("book_id", "idx");

-- CreateIndex
CREATE INDEX "progress_user_id_idx" ON "progress"("user_id");

-- CreateIndex
CREATE INDEX "bookmarks_book_id_idx" ON "bookmarks"("book_id");

-- CreateIndex
CREATE INDEX "device_sources_book_id_idx" ON "device_sources"("book_id");

-- CreateIndex
CREATE UNIQUE INDEX "device_sources_device_id_book_id_key" ON "device_sources"("device_id", "book_id");

-- AddForeignKey
ALTER TABLE "chapters" ADD CONSTRAINT "chapters_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "progress" ADD CONSTRAINT "progress_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookmarks" ADD CONSTRAINT "bookmarks_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "device_sources" ADD CONSTRAINT "device_sources_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- =============================================================================
-- Everything below is NOT generated by Prisma. Edit by hand.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Ownership foreign keys into auth.users.
--
-- auth.users is owned by Supabase, so it is deliberately absent from
-- schema.prisma — letting Prisma manage that table would be dangerous. The
-- columns are plain uuids in the Prisma model and get their referential
-- integrity here instead.
-- ---------------------------------------------------------------------------
ALTER TABLE "books"          ADD CONSTRAINT "books_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users ("id") ON DELETE CASCADE;
ALTER TABLE "chapters"       ADD CONSTRAINT "chapters_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users ("id") ON DELETE CASCADE;
ALTER TABLE "progress"       ADD CONSTRAINT "progress_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users ("id") ON DELETE CASCADE;
ALTER TABLE "bookmarks"      ADD CONSTRAINT "bookmarks_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users ("id") ON DELETE CASCADE;
ALTER TABLE "device_sources" ADD CONSTRAINT "device_sources_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users ("id") ON DELETE CASCADE;

-- ---------------------------------------------------------------------------
-- updated_at maintenance.
--
-- Prisma's @updatedAt is applied by Prisma Client, which never runs here, so
-- the database has to do it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS books_touch_updated_at ON "books";
CREATE TRIGGER books_touch_updated_at
  BEFORE UPDATE ON "books"
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Row-level security.
--
-- This is what makes it safe to ship the anon key to the browser: every row is
-- scoped to the signed-in user, enforced by Postgres rather than by app code.
-- ---------------------------------------------------------------------------
ALTER TABLE "books"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "chapters"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "progress"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bookmarks"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "device_sources" ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['books', 'chapters', 'progress', 'bookmarks', 'device_sources']
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_owner_all', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL
         USING (auth.uid() = user_id)
         WITH CHECK (auth.uid() = user_id)',
      t || '_owner_all', t
    );
  END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- Cover art storage. Covers are small images, unlike the audio.
-- Objects live at:  covers/<user_id>/<book_id>.<ext>
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('covers', 'covers', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "covers public read"  ON storage.objects;
DROP POLICY IF EXISTS "covers owner write"  ON storage.objects;
DROP POLICY IF EXISTS "covers owner update" ON storage.objects;
DROP POLICY IF EXISTS "covers owner delete" ON storage.objects;

CREATE POLICY "covers public read" ON storage.objects
  FOR SELECT USING (bucket_id = 'covers');

CREATE POLICY "covers owner write" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'covers'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "covers owner update" ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'covers'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "covers owner delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'covers'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
