-- =============================================================================
-- Per-user settings.
--
-- Top half generated from prisma/schema.prisma via `npm run db:diff`.
-- Bottom half is hand-written: the auth foreign key and RLS, neither of which
-- Prisma can express.
-- =============================================================================

-- CreateTable
CREATE TABLE "user_settings" (
    "user_id" UUID NOT NULL,
    "autoplay_next" BOOLEAN NOT NULL DEFAULT true,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_settings_pkey" PRIMARY KEY ("user_id")
);

-- =============================================================================
-- Not generated by Prisma.
-- =============================================================================
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users ("id") ON DELETE CASCADE;

ALTER TABLE "user_settings" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_settings_owner_all ON public.user_settings;
CREATE POLICY user_settings_owner_all ON public.user_settings
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
