-- CreateTable
CREATE TABLE "quotes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "book_id" UUID,
    "text" TEXT NOT NULL,
    "note" TEXT,
    "author" TEXT,
    "quoted_author" TEXT,
    "chapter_idx" INTEGER,
    "position_sec" DOUBLE PRECISION,
    "clip_start_sec" DOUBLE PRECISION,
    "clip_end_sec" DOUBLE PRECISION,
    "transcribed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "quotes_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "quotes_user_id_created_at_idx" ON "quotes"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "quotes_book_id_idx" ON "quotes"("book_id");

-- AddForeignKey
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- =============================================================================
-- Not generated by Prisma.
-- =============================================================================
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users ("id") ON DELETE CASCADE;

ALTER TABLE "quotes" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS quotes_owner_all ON public.quotes;
CREATE POLICY quotes_owner_all ON public.quotes
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Same trigger the other tables use, so updated_at is maintained by the
-- database rather than by every caller remembering to set it.
DROP TRIGGER IF EXISTS quotes_touch_updated_at ON public.quotes;
CREATE TRIGGER quotes_touch_updated_at BEFORE UPDATE ON public.quotes
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- Free-text search across the words, who said them and who relayed them.
CREATE INDEX IF NOT EXISTS quotes_text_search_idx ON public.quotes
  USING gin (to_tsvector('english',
    coalesce("text", '') || ' ' || coalesce(author, '') || ' ' || coalesce(quoted_author, '')));
